version: '3'
services:
  #Servicio ejemplo para remitir algunos logs. Prescindible.
  cliente-ejemplo:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: httpd.access
    depends_on:
      - fluentd

  fluentd:
    build: ./Dockerfiles/fluentd/
    volumes:
      - ./Dockerfiles/fluentd/config:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      # Puertos para remitir mensajes de log de aplicaciones
      - "24224:24224"
      - "24224:24224/udp"
      # Puerto al que remitir mensajes de syslog
      - "5140:5140/udp"
      - "5141:5141/udp"
    depends_on:
      - graylog
  
  elasticsearch:
    build: ./Dockerfiles/elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9350:9350"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m

  graylog:
    build: ./Dockerfiles/graylog/
    ports:
      - 9000:9000
      - 1514:1514/udp
      - 12201:12201/udp
      - 12900:12900
    links:
      - elasticsearch
      - mongo
    depends_on:
      - elasticsearch
      - mongo
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://test.santisteban.link:9000/api
    volumes:
      - ./datos/graylog/plugins:/usr/share/graylog/plugin
    # En caso de warning de número de ficheros abiertos.
    # ulimits:
    #   nofile:
    #     soft: "64000"
    #     hard: "64000"

  mongo:
    image: "mongo:3"
    volumes:
      - ./datos/mongodb:/data/db